# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'amapDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

 pod 'AMapNavi'
 pod 'AMapSearch'

  # Pods for amapDemo

  target 'amapDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'amapDemoUITests' do
    # Pods for testing
  end

end
